# Generated by Django 5.2.5 on 2025-08-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_description'),
        ('students', '0003_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
